openapi: 3.0.0
info:
  version: 1.0.0
  title: UShare
paths:
  "/member":
    post:
      tags:
        - "メンバー情報登録API"
      summary:
        "メンバー情報登録取得API"
      description:
        "指定したIDのユーザのメンバー情報登を登録します。"
      parameters:
        - name: "email"
          in: "formData"
          description: "ユーザのメールアドレス"
          required: true
          type: "string"
        - name: "pass"
          in: "formData"
          description: "ユーザのパスワード"
          required: true
          type: "string"
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  no:
                    type: "int"
                  name:
                    type: "string"
                  type:
                    type: "string"
                  comment:
                    type: "int  "
                example:
                  id: "1"
                  role: "usr"
                  pass: "123456password"
                  pass_reset: "1"
        400:
          description: "BadRequest"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  status:
                    type: "string"
                    example: "BAD_REQUEST"
                  message:
                    type: "string"
                    example: "BAD_REQUEST"
        404:
          desctiption: "NotFound"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  status:
                    type: "string"
                    example: "NOT_FOUND"
                  message:
                    type: "string"
                    example: "NOT_FOUND"
  "/pass":
    post:
      tags:
        - "ログイン情報取得API"
      summary:
        "ログイン情報取得API"
      description:
        "指定したIDのユーザを検索・パスワードチェックし、ログイン情報を取得します。"
      parameters:
        - name: "email"
          in: "formData"
          description: "ユーザのメールアドレス"
          required: true
          type: "string"
        - name: "pass"
          in: "formData"
          description: "ユーザのパスワード"
          required: true
          type: "string"
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  no:
                    type: "int"
                  name:
                    type: "string"
                  type:
                    type: "string"
                  comment:
                    type: "int  "
                example:
                  id: "1"
                  role: "usr"
                  pass: "123456password"
                  pass_reset: "1"
        400:
          description: "BadRequest"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  status:
                    type: "string"
                    example: "BAD_REQUEST"
                  message:
                    type: "string"
                    example: "BAD_REQUEST"
        404:
          desctiption: "NotFound"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  status:
                    type: "string"
                    example: "NOT_FOUND"
                  message:
                    type: "string"
                    example: "NOT_FOUND"