openapi: 3.0.0
info:
  version: 1.0.0
  title: UShare
paths:
  "/memberinfo/{memberId}:":
    post:
      tags:
        - "メンバー情報取得API"
      summary:
        "メンバー情報取得API"
      description:
        "指定したIDのユーザのメンバー情報を取得します。"
      parameters:
        - name: "memberId"
          in: "path"
          description: "取得したいメンバーのID"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: "int"
                  full_name:
                    type: "string"
                  birthday:
                    type: "string"
                  university:
                    type: "string"
                  major:
                    type: "string"
                  link1:
                    type: "string"
                  link2:
                    type: "string"
                  link3:
                    type: "string"
                  hobby:
                    type: array
                    items:
                      type: string
                  places_you_lived:
                    type: array
                    items:
                      type: string
                example:
                  id: "1"
                  full_name: "Yamada Taro"
                  birthday: "04/01"
                  university: "Waseda University"
                  major: "Architecture"
                  location: "U Share Nishiwaseda"
                  living_period: "2023 Spring to 2024 Fall"
                  link1: "(InstagramURL)"
                  link2: "(FacebookURL)"
                  link3: "(LinkedInURL)"
                  hobby:
                    - tennis
                    - fishing
                    - camp
                  places_you_lived:
                    - NewYork
                    - Pari
                    - Venetia
        400:
          description: "BadRequest"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  status:
                    type: "string"
                    example: "BAD_REQUEST"
                  message:
                    type: "string"
                    example: "BAD_REQUEST"
        404:
          desctiption: "NotFound"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  status:
                    type: "string"
                    example: "NOT_FOUND"
                  message:
                    type: "string"
                    example: "NOT_FOUND"
  "/pass":
    post:
      tags:
        - "ログイン情報取得API"
      summary:
        "ログイン情報取得API"
      description:
        "指定したIDのユーザを検索・パスワードチェックし、ログイン情報を取得します。"
      parameters:
        - name: "email"
          in: "formData"
          description: "ユーザのメールアドレス"
          required: true
          type: "string"
        - name: "pass"
          in: "formData"
          description: "ユーザのパスワード"
          required: true
          type: "string"
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  no:
                    type: "int"
                  name:
                    type: "string"
                  type:
                    type: "string"
                  comment:
                    type: "int  "
                example:
                  id: "1"
                  role: "usr"
                  pass: "123456password"
                  pass_reset: "1"
        400:
          description: "BadRequest"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  status:
                    type: "string"
                    example: "BAD_REQUEST"
                  message:
                    type: "string"
                    example: "BAD_REQUEST"
        404:
          desctiption: "NotFound"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  status:
                    type: "string"
                    example: "NOT_FOUND"
                  message:
                    type: "string"
                    example: "NOT_FOUND"